"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateCreativeContent = void 0;
const openai_1 = require("openai");
const functions = require("firebase-functions");
// Initialize OpenAI Client
// Note: In production, use functions.config().openai.key
const openai = new openai_1.default({
    apiKey: process.env.OPENAI_API_KEY || 'mock-key',
});
const generateCreativeContent = async (platform, topic, tone, additionalInstructions) => {
    if (!process.env.OPENAI_API_KEY) {
        console.warn('No OpenAI API Key found. Returning mock content.');
        return mockContentGeneration(platform, topic, tone);
    }
    try {
        const completion = await openai.chat.completions.create({
            messages: [
                {
                    role: 'system',
                    content: `You are an expert social media marketer. Generate a ${tone} post for ${platform}.`
                },
                {
                    role: 'user',
                    content: `Topic: ${topic}\nAdditional Instructions: ${additionalInstructions || 'None'}`
                }
            ],
            model: 'gpt-4',
        });
        return completion.choices[0].message.content;
    }
    catch (error) {
        console.error('Error generating content:', error);
        throw new functions.https.HttpsError('internal', 'Failed to generate content');
    }
};
exports.generateCreativeContent = generateCreativeContent;
const mockContentGeneration = (platform, topic, tone) => {
    return `[MOCK ${platform} POST]\n\nTopic: ${topic}\nTone: ${tone}\n\nHere is a creative caption that would normally be generated by AI. It includes emojis 🚀 and hashtags #growth #marketing.`;
};
//# sourceMappingURL=ai.js.map